### ISSUE TITLE
Installation instructions for version 0.0.3 are incorrect

### ISSUE THREAD

**Issue by Gamebuster19901** [srt32/git-actions#6]
The installation instructions for version 0.0.3 are incorrect. It will install version 0.0.2 instead of version 0.0.3.

![image](https://user-images.githubusercontent.com/7155747/68380317-98f39100-011d-11ea-8a87-e235f70a2eb7.png)

**Comment by srt32** [comment]
Where are you seeing that UI? When I go to https://github.com/marketplace/actions/git-actions, I see the following:


<img width="741" alt="Screen Shot 2019-11-07 at 9 13 54 AM" src="https://user-images.githubusercontent.com/2181356/68406372-f0562900-013e-11ea-9877-97a9fa2ea63f.png">

**Comment by Gamebuster19901** [comment]
1. Go to any repository you own that has actions enabled
2. click [Actions]
3. click [New workflow]
4. click [Set up a workflow yourself]
5. in the right panel, search "git actions"
6. click [git Actions]

**Comment by srt32** [comment]
Thanks for explaining! Looks like it's a GitHub bug as the readme itself is up to date and correct (as shown at the Marketplace url).

**Comment by Gamebuster19901** [comment]
Issue appears to be resolved
